packages:
  - 'modules/projects/**/node_modules/*
  - 'modules/projects/*/node_modules/*'
  - 'apps/**/node_modules/*'
  - 'apps/*/node_modules/*'
  - 'runtime/**/node_modules/*'
  - 'runtime/*/node_modules/*'
  - 'runtime/node_modules/*'
  - 'node_modules/*'
